hospitaljobsdelhi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('user/', include('users.urls', namespace="users"))
]

users/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path('login/', views.login, name="login")
]

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', TemplateView.as_view(template_name="web/about_us.html"), name='about'),
    path('services/', TemplateView.as_view(template_name='web/services.html'), name='services'),
    path('blog/', TemplateView.as_view(template_name='web/blog.html'), name='blog'),
    path('gallery/', TemplateView.as_view(template_name='web/gallery.html'), name='gallery'),
    path('contact/', TemplateView.as_view(template_name='web/contact_us.html'), name='contact'),
    path('register/', views.register, name='register'),
    path('recruit/', views.recruit, name="recruit"),
    path('<int:jid>/get_resume/', views.get_resume, name="get_resume")
]

users/models.py
from django.db import models

# Create your models here.

web/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.html import format_html
from django.urls import reverse
from django.utils import timezone
# Create your models here.

GENDER_CHOICES = [
    ('', 'Select Gender'),
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other')
]

class JobSeeker(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, blank=False)
    phone = models.CharField(max_length=10, default=None)
    email = models.EmailField(max_length=50, default=None)
    qualification = models.CharField(max_length=50, blank=True)
    speciality = models.CharField(max_length=50)
    experience = models.CharField(max_length=50)
    current_organization = models.CharField(max_length=50, blank=True)
    expected_salary = models.IntegerField(blank=True, null=True)
    resume = models.FileField(upload_to="uploads/", blank=True, null=True)
    applied_at = models.DateTimeField(default=timezone.now)
    
    def file_link(self):
        if self.resume:
            return format_html(f"<a href='{reverse('web:get_resume', kwargs={'jid':self.id})}'>download</a>")
        else:
            return "No attachment"

    file_link.allow_tags = True


class JobPosting(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    contact_no = models.CharField(max_length=10)
    contact_email = models.EmailField(max_length=50)
    organization_name = models.CharField(max_length=50)
    required_qualification = models.TextField(max_length=50, blank=True)
    required_experience = models.CharField(max_length=50, blank=True)
    salary_offering = models.CharField(max_length=20, blank=True)
    posted_at = models.DateTimeField(default=timezone.now)

web/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from .models import JobSeeker, JobPosting

class JobSeekerForm(ModelForm):
    class Meta:
        model = JobSeeker
        exclude = ('applied_at',)
        # widgets = {
        #     'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        # }

    def __init__(self, *args, **kwargs):
        super(JobSeekerForm, self).__init__(*args, **kwargs)
        self.fields['resume'].widget.attrs={'accept': '.pdf'}
        for visible in self.visible_fields():
            elem = visible.field.widget
            elem.attrs['class'] = 'form-control'
            elem.attrs['placeholder'] = visible.field.label

class JobPostingForm(ModelForm):
    class Meta:
        model = JobPosting
        exclude = ('posted_at',)
        # widgets = {
        #     'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        # }

    def __init__(self, *args, **kwargs):
        super(JobPostingForm, self).__init__(*args, **kwargs)
        self.fields['required_qualification'].widget.attrs={'rows':3}
        for visible in self.visible_fields():
            elem = visible.field.widget
            elem.attrs['class'] = 'form-control'
            elem.attrs['placeholder'] = visible.field.label

users/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, 'users/widgets.html')

web/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import mimetypes
from . import forms
from . import models
from . import tasks
from django.views.generic import ListView

# Create your views here.
class HomeView(ListView):
    model = models.JobSeeker
    context_object_name = 'registrations'
    template_name = 'web/home.html'

    def head(self, *args, **kwargs):
        last_applications = self.get_queryset().latest('applied_at')
        response = HttpResponse(
            # RFC 1123 date format.
            headers={'Last-Modified': last_application.applied_at.strftime('%a, %d %b %Y %H:%M:%S GMT')},
        )
        return response

def register(request):
    if request.method=="POST":
        f = forms.JobSeekerForm(request.POST, request.FILES)
        if f.is_valid():
            data = f.save()
            tasks.send_custom_mail(data)
            return render(request, 'web/submission_success.html', {'ref_id': f"HSD-JS-{data.id}"})
    return render(request, 'web/register.html', {'job_form': forms.JobSeekerForm(), 'current_page':'register'})

def recruit(request):
    if request.method=="POST":
        f = forms.JobPostingForm(request.POST, request.FILES)
        if f.is_valid():
            data = f.save()
            return render(request, 'web/submission_success.html', {'ref_id': f"HSD-JP-{data.id}"})
    return render(request, 'web/recruit.html', {'posting_form': forms.JobPostingForm()})

def get_resume(request, jid=0):
    if request.user.is_superuser:
        try:
            current_jobseeker = models.JobSeeker.objects.get(id=jid)
            if current_jobseeker.resume:
                filename = current_jobseeker.resume.name
                response = HttpResponse(current_jobseeker.resume, content_type=mimetypes.guess_type(filename)[0])
                response['Content-Length'] = current_jobseeker.resume.size
                response['Content-Disposition'] = "attachment; filename=" + filename
                return response
        except:
            pass
    return redirect('/')

users/templates/users/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lumino - Login</title>
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/datepicker3.css" rel="stylesheet">
	<link href="css/styles.css" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">Log in</div>
				<div class="panel-body">
					<form role="form">
						<fieldset>
							<div class="form-group">
								<input class="form-control" placeholder="E-mail" name="email" type="email" autofocus="">
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Password" name="password" type="password" value="">
							</div>
							<div class="checkbox">
								<label>
									<input name="remember" type="checkbox" value="Remember Me">Remember Me
								</label>
							</div>
							<a href="index.html" class="btn btn-primary">Login</a></fieldset>
					</form>
				</div>
			</div>
		</div><!-- /.col-->
	</div><!-- /.row -->	
	

<script src="js/jquery-1.11.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lumino - Login</title>
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/datepicker3.css" rel="stylesheet">
	<link href="css/styles.css" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">Log in</div>
				<div class="panel-body">
					<form role="form">
						<fieldset>
							<div class="form-group">
								<input class="form-control" placeholder="E-mail" name="email" type="email" autofocus="">
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Password" name="password" type="password" value="">
							</div>
							<div class="checkbox">
								<label>
									<input name="remember" type="checkbox" value="Remember Me">Remember Me
								</label>
							</div>
							<a href="index.html" class="btn btn-primary">Login</a></fieldset>
					</form>
				</div>
			</div>
		</div><!-- /.col-->
	</div><!-- /.row -->	
	

<script src="js/jquery-1.11.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
</body>
</html>

web/templates/web/footer.html
{% load static %}
<!-- ################# Footer Starts Here#######################--->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                <h2>About Us</h2>
                <p>
                    We are one of the leading providers of Healthcare staffing
                    solutions PAN India, offering a wide range of Healthcare and
                    medical jobs. Hiring the right people at the right time is
                    what we do. We serve the employer as well as an employee to
                    fulfill their requirements.
                </p>
                <p>
                    If you are an employer, we offer you the entire recruitment
                    process including background verification, which will save
                    your valuable time and recruitment cost.
                </p>
            </div>
            <div class="col-md-4 col-sm-12">
                <h2>Useful Links</h2>
                <ul class="list-unstyled link-list">
                    <li>
                        <a ui-sref="about" href="{% url 'web:about' %}"
                            >About us</a
                        ><i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a ui-sref="portfolio" href="{% url 'web:services' %}"
                            >Services</a
                        ><i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a ui-sref="products" href="{% url 'web:blog' %}"
                            >Blog</a
                        ><i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a ui-sref="gallery" href="{% url 'web:gallery' %}"
                            >Gallery</a
                        ><i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a ui-sref="contact" href="{% url 'web:contact' %}"
                            >Contact us</a
                        ><i class="fa fa-angle-right"></i>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-12 map-img">
                <h2>Contact Us</h2>
                <address class="md-margin-bottom-40">
                    Hospital Jobs Delhi <br />
                    Akshardjam (K.K District) <br />
                    New Delhi, IND <br />
                    Pin: 110021 <br/>
                    Phone: +91-9718706679 <br />
                    Email:
                    <a href="mailto:info@anybiz.com" class=""
                        >hospitaljobsdelhi@gmail.com</a
                    ><br />
                    Web:
                    <a href="smart-eye.html" class=""
                        >www.hospitaljobsdelhi.com</a
                    >
                </address>
            </div>
        </div>
    </div>
</footer>
<div class="copy">
    <div class="container">
        <a href="https://www.smarteyeapps.com/"
            >2015 &copy; All Rights Reserved
            <!-- | Designed and Developed by
            Smarteyeapps -->
        </a>
<!-- 
        <span>
            <a><i class="fab fa-github"></i></a>
            <a><i class="fab fa-google-plus-g"></i></a>
            <a><i class="fab fa-pinterest-p"></i></a>
            <a><i class="fab fa-twitter"></i></a>
            <a><i class="fab fa-facebook-f"></i></a>
        </span> -->
    </div>
</div>
<script src="{% static 'web/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'web/js/popper.min.js' %}"></script>
<script src="{% static 'web/js/bootstrap.min.js' %}"></script>
<script src="{% static 'web/plugins/scroll-fixed/jquery-scrolltofixed-min.js' %}"></script>
<script src="{% static 'web/js/script.js' %}"></script>

web/templates/web/form-main.html
{% extends 'web/main.html' %}
{% load static %}
{% block title %}About us{%endblock %} {% block content %}
<link rel="stylesheet" href="{% static 'web/css/datepicker.css' %}" />
<link rel="stylesheet" href="{% static 'web/css/formstyle.css' %}" />
<div class="inner-layer">
    <div class="container">
        <div class="row no-margin">
            <div class="col-sm-7">
                <div class="content">
                    <h1>Leverage Delhi's biggest Hosbital jobs firm</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Morbi sagittis at lacus at rhoncus. Integer pharetra
                        lacus vitae sapien blandit eleifend.
                    </p>
                    <h2>For Help Call : +189-123-453</h2>
                </div>
            </div>
            {% block myform %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %} {% block otherscripts %}
<script src="{% static 'web/js/bootstrap-datepicker.js' %}"></script>
<script>
    $(document).ready(function () {
        $("#dat").datepicker();
    });
</script>
{% endblock %}

web/templates/web/header.html
{% load static %}
<!-- ################# Header Starts Here#######################--->
<header>
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 left-item">
                    <ul>
                        <li>
                            <i class="fas fa-envelope-square"></i>
                            hospitaljobsdelhi@gmail.com
                        </li>
                        <li>
                            <i class="fas fa-phone-square"></i> +91-9718706679
                        </li>
                    </ul>
                </div>
                <div class="col-lg-5 d-none d-lg-block right-item">
                    <ul>
                        <li>
                            <a><i class="fab fa-github"></i></a>
                        </li>
                        <li>
                            <a><i class="fab fa-google-plus-g"></i></a>
                        </li>
                        <li>
                            <a><i class="fab fa-pinterest-p"></i></a>
                        </li>
                        <li>
                            <a><i class="fab fa-twitter"></i></a>
                        </li>
                        <li>
                            <a><i class="fab fa-facebook-f"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="nav-head" class="header-nav">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-3 no-padding col-sm-12 nav-img">
                    <a href="{% url 'web:home' %}"
                        ><img src="{% static 'web/images/logo.png' %}" alt=""
                    /></a>
                    <a data-toggle="collapse" data-target="#menu" href="#menu"
                        ><i class="fas d-block d-md-none small-menu fa-bars"></i
                    ></a>
                </div>
                <div
                    id="menu"
                    class="col-lg-8 col-md-9 d-none d-md-block nav-item"
                >
                    <ul>
                        <li><a href="{% url 'web:home' %}">Home</a></li>
                        <li><a href="{% url 'web:about' %}">About Us</a></li>
                        <li><a href='{% url "web:services" %}'>Services</a></li>
                        <li><a href="{% url 'web:blog' %}">Blog</a></li>
                        <li><a href="{% url 'web:gallery' %}">Gallery</a></li>
                        <li>
                            <a href="{% url 'web:contact' %}">Contact Us</a>
                        </li>
                        <li>
                            <div class="d-block d-lg-none appoint">
                                {% if current_page == "register" %}
                                <a
                                    href="{% url 'web:recruit' %}"
                                    class="btn btn-info"
                                    >Post a job opening</a
                                >
                                {% else %}
                                <a
                                    href="{% url 'web:register' %}"
                                    class="btn btn-info"
                                    >Register for free</a
                                >
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-2 d-none d-lg-block appoint">
                    {% if current_page == "register" %}
                    <a href="{% url 'web:recruit' %}" class="btn btn-info"
                        >Post a job opening</a
                    >
                    {% else %}
                    <a href="{% url 'web:register' %}" class="btn btn-info"
                        >Register for free</a
                    >
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>

web/templates/web/page_title.html
<!--  ************************* Page Title Starts Here ************************** -->
<div class="page-nav no-margin row">
    <div class="container">
        <div class="row">
            <h2>{{title}}</h2>
            <ul>
                <li>
                    <a href="#"><i class="fas fa-home"></i> Home</a>
                </li>
                <li><i class="fas fa-angle-double-right"></i> {{title}}</li>
            </ul>
        </div>
    </div>
</div>
<!-- ######## Page  Title End ####### -->

web/templates/web/recruit.html
{% extends 'web/form-main.html' %}
{% block myform %}
<div class="col-sm-5 order-first pt-5">
    <form class="form-data" method="POST" action="{% url 'web:recruit' %}">
        {% csrf_token %}
        <div class="form-head pt-3">
            <h2>Submit Job Requirement</h2>
        </div>
        <div class="form-body">
            <div class="row form-row">
                <div class="col-sm-6 pl-sm-0">
                    {{posting_form.first_name}}
                </div>
                <div class="col-sm-6 pr-sm-0">
                    {{posting_form.last_name}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-12 px-sm-0">
                    {{posting_form.organization_name}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-sm-7 pl-sm-0">
                    {{posting_form.contact_email}}
                </div>
                <div class="col-sm-5 pr-sm-0">
                    {{posting_form.contact_no}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-12 px-sm-0">
                    {{posting_form.required_qualification}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-sm-6 pl-sm-0">
                    {{posting_form.required_experience}}
                </div>
                <div class="col-sm-6 pr-sm-0">
                    {{posting_form.salary_offering}}
                </div>
            </div>
            <div class="row form-row">
                <button class="btn btn-success btn-appointment">
                    Post Requirement
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

web/templates/web/register.html
{% extends 'web/form-main.html' %}
{% block myform %}
<div class="col-sm-5">
    <form class="form-data" enctype="multipart/form-data" method="POST" action="{% url 'web:register' %}">
        {% csrf_token %}
        <div class="form-head">
            <h2>Register Now</h2>
        </div>
        <div class="form-body">
            <div class="row form-row">
                <div class="col-sm-6 pl-sm-0">
                    {{job_form.first_name}}
                </div>
                <div class="col-sm-6 pr-sm-0">
                    {{job_form.last_name}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-12 px-sm-0">
                    {{job_form.email}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-sm-7 pl-sm-0">
                    {{job_form.phone}}
                </div>
                <div class="col-sm-5 pr-sm-0">
                    {{job_form.gender}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-12 px-sm-0">
                    {{job_form.qualification}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-12 px-sm-0">
                    {{job_form.speciality}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-sm-6 pl-sm-0">
                    {{job_form.experience}}
                </div>
                <div class="col-sm-6 pr-sm-0">
                    {{job_form.expected_salary}}
                </div>
            </div>
            <div class="row form-row">
                <div class="col-sm-6 pr-sm-0">
                    {{job_form.current_company}}
                </div>
            </div>
            <h6 class="text-right">Upload Resume</h6>
            <div class="row form-row">
                <div class="col-12 px-sm-0">
                    {{job_form.resume}}
                </div>
            </div>
            <!-- <div class="row form-row">
                <input
                    id="dat"
                    type="text"
                    placeholder="Appointment Date"
                    class="form-control"
                    name="date"
                />
            </div> -->
            <div class="row form-row">
                <button class="btn btn-success btn-appointment">
                    Register
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

web/templates/web/services.html
{% extends 'web/main.html' %}
{% block title %}Services{% endblock %}
{% block content %}
{% include 'web/page_title.html' with title="Services" %}
{% include 'web/our_departments.html' %}
{% endblock %}

web/templates/web/slider.html
{% load static %}
<!-- ################# Slider Starts Here#######################--->
<div class="slider-detail">
    <div
        id="carouselExampleIndicators"
        class="carousel slide"
        data-ride="carousel"
    >
        <ol class="carousel-indicators">
            <li
                data-target="#carouselExampleIndicators"
                data-slide-to="0"
                class="active"
            ></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item">
                <img
                    class="d-block w-100"
                    src="{% static 'web/images/slider/slider_1.jpg' %}"
                    alt="First slide"
                />
                <div class="bg-light d-md-none" style="min-height:400px">
                    <div class="p-5">
                        <h5 class="animated bounceInDown">
                            Hire medical experts within minutes
                        </h5>
                        <hr/>
                        <p class="animated bounceInLeft">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Nullam justo neque, <br />
                            aliquet sit amet elementum vel, vehicula eget eros.
                            Vivamus arcu metus, mattis <br />
                            sed sagittis at, sagittis quis neque. Praesent.
                        </p>
                        <hr/>
                        <a href="{% url 'web:register' %}" class="btn btn-primary">
                            Register for free
                        </a>
                    </div>
                </div>
                <div class="carousel-caption fvgb d-none d-md-block">
                    <h5 class="animated bounceInDown">
                        Hire medical experts within minutes
                    </h5>
                    <p class="animated bounceInLeft">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Nullam justo neque, <br />
                        aliquet sit amet elementum vel, vehicula eget eros.
                        Vivamus arcu metus, mattis <br />
                        sed sagittis at, sagittis quis neque. Praesent.
                    </p>

                    <div class="row vbh">
                        <a href="{% url 'web:recruit' %}">
                            <div class="btn btn-info animated bounceInUp">
                                Post a job Requirement
                            </div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="carousel-item active">
                <img
                    class="d-block w-100"
                    src="{% static 'web/images/slider/slider_3.jpg' %}"
                    alt="Third slide"
                />
                <div class="bg-light d-md-none" style="min-height:400px">
                    <div class="p-5">
                        <h5 class="animated bounceInDown">
                            We help you find your dream job
                        </h5>
                        <hr/>
                        <p class="animated bounceInLeft">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Nullam justo neque, <br />
                            aliquet sit amet elementum vel, vehicula eget eros.
                            Vivamus arcu metus, mattis <br />
                            sed sagittis at, sagittis quis neque. Praesent.
                        </p>
                        <hr/>
                        <a href="{% url 'web:recruit' %}" class="btn btn-primary">
                            Post a job Requirement
                        </a>
                    </div>
                </div>
                <div>
                    <div class="carousel-caption vdg-cur d-none d-md-block">
                        <h5 class="animated bounceInDown">
                            We help you find your dream job
                        </h5>
                        <p class="animated bounceInLeft">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Nullam justo neque, <br />
                            aliquet sit amet elementum vel, vehicula eget eros.
                            Vivamus arcu metus, mattis <br />
                            sed sagittis at, sagittis quis neque. Praesent.
                        </p>
                        <div class="row vbh">
                            <a href="{% url 'web:register' %}">
                                <div class="btn btn-info animated bounceInUp">
                                    Register as a job seeker
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <a
                class="carousel-control-prev"
                href="#carouselExampleIndicators"
                role="button"
                data-slide="prev"
            >
                <span
                    class="carousel-control-prev-icon"
                    aria-hidden="true"
                ></span>
                <span class="sr-only">Previous</span>
            </a>
            <a
                class="carousel-control-next"
                href="#carouselExampleIndicators"
                role="button"
                data-slide="next"
            >
                <span
                    class="carousel-control-next-icon"
                    aria-hidden="true"
                ></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

web/templates/web/submission_success.html
{% extends 'web/main.html' %} {% block title %}Contact Us{% endblock %} 
{% block content %}
<!-- ################# Our Blog Starts Here#######################--->
<div class="container">
    <div
        class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light"
    >
        <div class="p-lg-5 mx-auto my-5">
            <h1 class="display-4 font-weight-normal">Submission Succesful</h1>
            <hr/>
            <p class="lead font-weight-normal">
                We have recorded your input and we will contact you soon. Your reference id is {{ref_id}}, feel free to contact us at our Contact E-mail and Phone No.
            </p>
            <a class="btn btn-outline-secondary m-3" href="/">Continue</a>
        </div>
        <div class="product-device box-shadow d-none d-md-block"></div>
        <div
            class="product-device product-device-2 box-shadow d-none d-md-block"
        ></div>
    </div>
</div>
{% endblock %}

web/templates/web/test.html
<form method="POST" action="{% url 'web:testform' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.file_document}}
    <input type="submit" value="send"/>
</form>